const currencies = [
  { label: "Afghan Afghani", value: "AFN" },
  { label: "Albanian Lek", value: "ALL" },
  { label: "Algerian Dinar", value: "DZD" },
  { label: "Angolan Kwanza", value: "AOA" },
  { label: "Argentine Peso", value: "ARS" },
  { label: "Armenian Dram", value: "AMD" },
  { label: "Australian Dollar", value: "AUD" },
  { label: "Azerbaijani Manat", value: "AZN" },
  { label: "Bahamian Dollar", value: "BSD" },
  { label: "Bahraini Dinar", value: "BHD" },
  { label: "Bangladeshi Taka", value: "BDT" },
  { label: "Barbadian Dollar", value: "BBD" },
  { label: "Belarusian Ruble", value: "BYN" },
  { label: "Belize Dollar", value: "BZD" },
  { label: "Bermudian Dollar", value: "BMD" },
  { label: "Bhutanese Ngultrum", value: "BTN" },
  { label: "Bolivian Boliviano", value: "BOB" },
  { label: "Bosnia and Herzegovina Convertible Mark", value: "BAM" },
  { label: "Botswana Pula", value: "BWP" },
  { label: "Brazilian Real", value: "BRL" },
  { label: "Brunei Dollar", value: "BND" },
  { label: "Bulgarian Lev", value: "BGN" },
  { label: "Burundian Franc", value: "BIF" },
  { label: "Cambodian Riel", value: "KHR" },
  { label: "Canadian Dollar", value: "CAD" },
  { label: "Cape Verdean Escudo", value: "CVE" },
  { label: "Cayman Islands Dollar", value: "KYD" },
  { label: "Central African CFA Franc", value: "XAF" },
  { label: "CFP Franc", value: "XPF" },
  { label: "Chilean Peso", value: "CLP" },
  { label: "Chinese Yuan", value: "CNY" },
  { label: "Colombian Peso", value: "COP" },
  { label: "Comorian Franc", value: "KMF" },
  { label: "Congolese Franc", value: "CDF" },
  { label: "Costa Rican Colón", value: "CRC" },
  { label: "Croatian Kuna", value: "HRK" },
  { label: "Cuban Peso", value: "CUP" },
  { label: "Czech Koruna", value: "CZK" },
  { label: "Danish Krone", value: "DKK" },
  { label: "Djiboutian Franc", value: "DJF" },
  { label: "Dominican Peso", value: "DOP" },
  { label: "Egyptian Pound", value: "EGP" },
  { label: "Eritrean Nakfa", value: "ERN" },
  { label: "Eswatini Lilangeni", value: "SZL" },
  { label: "Ethiopian Birr", value: "ETB" },
  { label: "Euro", value: "EUR" },
  { label: "Fiji Dollar", value: "FJD" },
  { label: "Gambian Dalasi", value: "GMD" },
  { label: "Georgian Lari", value: "GEL" },
  { label: "Ghanaian Cedi", value: "GHS" },
  { label: "Guatemalan Quetzal", value: "GTQ" },
  { label: "Guinean Franc", value: "GNF" },
  { label: "Guyanese Dollar", value: "GYD" },
  { label: "Haitian Gourde", value: "HTG" },
  { label: "Honduran Lempira", value: "HNL" },
  { label: "Hong Kong Dollar", value: "HKD" },
  { label: "Hungarian Forint", value: "HUF" },
  { label: "Icelandic Króna", value: "ISK" },
  { label: "Indian Rupee", value: "INR" },
  { label: "Indonesian Rupiah", value: "IDR" },
  { label: "Iranian Rial", value: "IRR" },
  { label: "Iraqi Dinar", value: "IQD" },
  { label: "Israeli New Shekel", value: "ILS" },
  { label: "Jamaican Dollar", value: "JMD" },
  { label: "Japanese Yen", value: "JPY" },
  { label: "Jordanian Dinar", value: "JOD" },
  { label: "Kazakhstani Tenge", value: "KZT" },
  { label: "Kenyan Shilling", value: "KES" },
  { label: "Kuwaiti Dinar", value: "KWD" },
  { label: "Kyrgyzstani Som", value: "KGS" },
  { label: "Lao Kip", value: "LAK" },
  { label: "Lebanese Pound", value: "LBP" },
  { label: "Lesotho Loti", value: "LSL" },
  { label: "Liberian Dollar", value: "LRD" },
  { label: "Libyan Dinar", value: "LYD" },
  { label: "Macanese Pataca", value: "MOP" },
  { label: "Malagasy Ariary", value: "MGA" },
  { label: "Malawian Kwacha", value: "MWK" },
  { label: "Malaysian Ringgit", value: "MYR" },
  { label: "Maldivian Rufiyaa", value: "MVR" },
  { label: "Mauritanian Ouguiya", value: "MRU" },
  { label: "Mauritian Rupee", value: "MUR" },
  { label: "Mexican Peso", value: "MXN" },
  { label: "Moldovan Leu", value: "MDL" },
  { label: "Mongolian Tögrög", value: "MNT" },
  { label: "Moroccan Dirham", value: "MAD" },
  { label: "Mozambican Metical", value: "MZN" },
  { label: "Myanmar Kyat", value: "MMK" },
  { label: "Namibian Dollar", value: "NAD" },
  { label: "Nepalese Rupee", value: "NPR" },
  { label: "New Zealand Dollar", value: "NZD" },
  { label: "Nicaraguan Córdoba", value: "NIO" },
  { label: "Nigerian Naira", value: "NGN" },
  { label: "North Korean Won", value: "KPW" },
  { label: "Norwegian Krone", value: "NOK" },
  { label: "Omani Rial", value: "OMR" },
  { label: "Pakistani Rupee", value: "PKR" },
  { label: "Panamanian Balboa", value: "PAB" },
  { label: "Papua New Guinean Kina", value: "PGK" },
  { label: "Paraguayan Guaraní", value: "PYG" },
  { label: "Peruvian Sol", value: "PEN" },
  { label: "Philippine Peso", value: "PHP" },
  { label: "Polish Złoty", value: "PLN" },
  { label: "Qatari Riyal", value: "QAR" },
  { label: "Russian Ruble", value: "RUB" },
  { label: "Saudi Riyal", value: "SAR" },
  { label: "South African Rand", value: "ZAR" },
  { label: "South Korean Won", value: "KRW" },
  { label: "Swiss Franc", value: "CHF" },
  { label: "United States Dollar", value: "USD" },
];

export default currencies;
